### ISSUE TITLE
sam_quantized.onnx 和官方导出的模型有什么区别吗

### ISSUE THREAD

**Issue by wz131486** [haibingtown/segment-matting#1]
sam_quantized.onnx 比官方的效果要好，请问是做了哪些操作？

**Comment by haibingtown** [comment]
Based on the input and output parameters required by the model, the version of the model in the official demo is different from the version provided for download on GitHub. The latter should be an updated version, and I have only adapted the calling method of the model from the demo to work with the latest version.
