### ISSUE TITLE
what is image_to_mask

### ISSUE THREAD

**Issue by GH-W5** [haibingtown/segment-matting#4]

**Comment by GH-W5** [comment]
read image

**Comment by timiil** [comment]
same question ... 从何处引入这个函数啊?

**Comment by GH-W5** [comment]
应该是读取mask，实际上没有用到image_to_mask，我把他给注释了

**Comment by timiil** [comment]
谢谢

**Comment by timiil** [comment]
那matting.py您老人家改成什么样子了？

**Comment by GH-W5** [comment]
`from pymatting import cutout
import numpy as np
import cv2

# from server.matting.utils import image_to_mask


def mask_to_trimap(mask, dilation_size=10, erosion_size=10):
    trimap = np.where(mask == 0, 0, 255)

    dilation_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (dilation_size, dilation_size))
    dilated_trimap = cv2.dilate(trimap.astype(np.uint8), dilation_kernel, iterations=1)

    erosion_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (erosion_size, erosion_size))
    final_trimap = cv2.erode(trimap.astype(np.uint8), erosion_kernel, iterations=1)

    # 计算膨胀之后的差异
    diff = dilated_trimap - final_trimap
    # 将膨胀多出来的部分像素值设为128
    final_trimap = final_trimap + np.where(diff > 0, 128, 0)

    return final_trimap

def matting(image, mask):
    # image = cv2.imread(image_path)
    # mask = image_to_mask(mask_path)
    mask = cv2.resize(mask, (image.shape[1], image.shape[0]))

    return mask

# image_path = 'assets/4.jpeg'
# mask_path = 'assets/4_mask.png'
# trimap_path = 'assets/4_trimp.png'
# cout_path = 'assets/4_mat_alpha.png'
#
# image = cv2.imread(image_path)
# mask = image_to_mask(mask_path)
# mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
# trimap = mask_to_trimap(mask, 20, 20)
# cv2.imwrite(trimap_path, trimap)
# cutout(
#     image_path,
#     trimap_path,
#     cout_path
# )
`

**Comment by GH-W5** [comment]
`
from pymatting import cutout
import numpy as np
import cv2

# from server.matting.utils import image_to_mask


def mask_to_trimap(mask, dilation_size=10, erosion_size=10):
    trimap = np.where(mask == 0, 0, 255)

    dilation_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (dilation_size, dilation_size))
    dilated_trimap = cv2.dilate(trimap.astype(np.uint8), dilation_kernel, iterations=1)

    erosion_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (erosion_size, erosion_size))
    final_trimap = cv2.erode(trimap.astype(np.uint8), erosion_kernel, iterations=1)

    # 计算膨胀之后的差异
    diff = dilated_trimap - final_trimap
    # 将膨胀多出来的部分像素值设为128
    final_trimap = final_trimap + np.where(diff > 0, 128, 0)

    return final_trimap

def matting(image, mask):
    # image = cv2.imread(image_path)
    # mask = image_to_mask(mask_path)
    mask = cv2.resize(mask, (image.shape[1], image.shape[0]))

    return mask

# image_path = 'assets/4.jpeg'
# mask_path = 'assets/4_mask.png'
# trimap_path = 'assets/4_trimp.png'
# cout_path = 'assets/4_mat_alpha.png'
#
# image = cv2.imread(image_path)
# mask = image_to_mask(mask_path)
# mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
# trimap = mask_to_trimap(mask, 20, 20)
# cv2.imwrite(trimap_path, trimap)
# cutout(
#     image_path,
#     trimap_path,
#     cout_path
# )
`

**Comment by GH-W5** [comment]
![image](https://github.com/haibingtown/segment-matting/assets/48881536/f1d0f404-0ec5-4685-bed1-eaa528ae55c2)

**Comment by timiil** [comment]
用三个单引号开始引用代码， 用三个单引号结束引用代码即可 ：）

**Comment by GH-W5** [comment]
'''
from pymatting import cutout
import numpy as np
import cv2

# from server.matting.utils import image_to_mask


def mask_to_trimap(mask, dilation_size=10, erosion_size=10):
    trimap = np.where(mask == 0, 0, 255)

    dilation_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (dilation_size, dilation_size))
    dilated_trimap = cv2.dilate(trimap.astype(np.uint8), dilation_kernel, iterations=1)

    erosion_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (erosion_size, erosion_size))
    final_trimap = cv2.erode(trimap.astype(np.uint8), erosion_kernel, iterations=1)

    # 计算膨胀之后的差异
    diff = dilated_trimap - final_trimap
    # 将膨胀多出来的部分像素值设为128
    final_trimap = final_trimap + np.where(diff > 0, 128, 0)

    return final_trimap

def matting(image, mask):
    # image = cv2.imread(image_path)
    # mask = image_to_mask(mask_path)
    mask = cv2.resize(mask, (image.shape[1], image.shape[0]))

    return mask

# image_path = 'assets/4.jpeg'
# mask_path = 'assets/4_mask.png'
# trimap_path = 'assets/4_trimp.png'
# cout_path = 'assets/4_mat_alpha.png'
#
# image = cv2.imread(image_path)
# mask = image_to_mask(mask_path)
# mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
# trimap = mask_to_trimap(mask, 20, 20)
# cv2.imwrite(trimap_path, trimap)
# cutout(
#     image_path,
#     trimap_path,
#     cout_path
# )
'''

**Comment by GH-W5** [comment]
`
import cv2

def matting(image, mask):
    mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
    return mask
`

**Comment by GH-W5** [comment]
```
import cv2

def matting(image, mask):
    mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
    return mask
```

**Comment by GH-W5** [comment]
```
from pymatting import cutout
import numpy as np
import cv2

# from server.matting.utils import image_to_mask


def mask_to_trimap(mask, dilation_size=10, erosion_size=10):
    trimap = np.where(mask == 0, 0, 255)

    dilation_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (dilation_size, dilation_size))
    dilated_trimap = cv2.dilate(trimap.astype(np.uint8), dilation_kernel, iterations=1)

    erosion_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (erosion_size, erosion_size))
    final_trimap = cv2.erode(trimap.astype(np.uint8), erosion_kernel, iterations=1)

    # 计算膨胀之后的差异
    diff = dilated_trimap - final_trimap
    # 将膨胀多出来的部分像素值设为128
    final_trimap = final_trimap + np.where(diff > 0, 128, 0)

    return final_trimap

def matting(image, mask):
    # image = cv2.imread(image_path)
    # mask = image_to_mask(mask_path)
    mask = cv2.resize(mask, (image.shape[1], image.shape[0]))

    return mask

# image_path = 'assets/4.jpeg'
# mask_path = 'assets/4_mask.png'
# trimap_path = 'assets/4_trimp.png'
# cout_path = 'assets/4_mat_alpha.png'
#
# image = cv2.imread(image_path)
# mask = image_to_mask(mask_path)
# mask = cv2.resize(mask, (image.shape[1], image.shape[0]))
# trimap = mask_to_trimap(mask, 20, 20)
# cv2.imwrite(trimap_path, trimap)
# cutout(
#     image_path,
#     trimap_path,
#     cout_path
# )
```

**Comment by timiil** [comment]
谢谢你
